#!/bin/bash
#$ -S /bin/sh
#$ -l h_data=20G,h_rt=10:00:00


time1=$( date "+%s" )

echo [Directory] `pwd`
echo [Machine] `uname -n`
echo [Start] `date`
echo [args] $*


output_dir=$1
s=$2
ref=/coppolalabshares/marisaprj01/Takeda/Pipeline/reference/human_g1k_v37.no_unlocalized_contigs.fasta
vcf=/coppolalabshares/marisaprj01/Takeda/Pipeline/dbSNP/dbsnp_138.b37.vcf


echo "Running:"
echo "gatk create indel intervals"


java -Xmx4g -Xms2g -Djava.io.tmpdir=/home/yqin/201505_ExomeSeq/tmp -jar /home/yqin/bin/GenomeAnalysisTK.jar -L /coppolalabshares/marisaprj01/Takeda/Pipeline/intervals/SeqCap_EZ_Exome_v3_primary.bed.intervals -o $output_dir/$s.realn.intervals.list -I $output_dir/$s.aln.dedup.bam -T RealignerTargetCreator -R $ref --known $vcf


time2=$( date "+%s" )
echo [deltat] $(( $time2 - $time1 ))
echo [End] `date`
